### ISSUE TITLE
Week2

### ISSUE THREAD

**Issue by SaschaVanEssen** [joelklein123/Project#2]
In je PROCESS.md hoeven geen plaatjes van je site (dat maakt het onoverzichtelijk). Focus op welke belangrijke beslissingen je die dag gemaakt hebt, niet op hoe ver je bent. Alle code moet in 1 map (daarbinnen mogen weer submappen) met uitzondering van je index.html, die mag in de root directory als je dat wilt

**Comment by joelklein123** [comment]
“In je PROCESS.md hoeven geen plaatjes van je site” – op de pagina van process staat het volgende: “We strongly advise you to include many figures in your process book, including photos of your sketches of potential designs, screen shots from different visualization tools you explored, inspirations of visualizations you found online, etc. Several images illustrating changes in your design or focus over time will be far more informative than text describing those changes. Instead, use text to describe the rationale behind the evolution of your project.” Daarom deed ik overal afbeeldingen bij, maar vanaf nu zal ik alleen beschrijven welke belangrijke beslissingen ik gemaakt heb.

Alle code staat nu in 1 map met submappen.

**Comment by SaschaVanEssen** [comment]
Je mag er wel plaatjes in doen, maar maak ze dan wat kleiner zodat het overzichtelijker is :) En dus niet over hoe ver je nu bent, maar over "different visualization tools you explored" en "sketches of potential designs" etc. Dus de overwegingen achter je site, en niet het resultaat
